'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Koala.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2DMember() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2DMember", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Analysis() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Analysis", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Beam() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Beam", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CreateXML() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CreateXML", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cross_link() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cross_link", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cross_section() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cross_section", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EdgeLoad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EdgeLoad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FreeLineLoad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FreeLineLoad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FreePointLoad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FreePointLoad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FreeSurfaceLoad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FreeSurfaceLoad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gap() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gap", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Hinge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hinge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot; standalone=&quot;yes&quot;?&gt;
        '''
        '''&lt;def_project xmlns=&quot;http://www.scia.cz&quot;&gt;
        '''   
        '''   &lt;def_container id=&quot;{AC021036-C943-4B46-88E4-72CFB9D9391C}&quot; clsid=&quot;{AC021036-C943-4B46-88E4-72CFB9D9391C}&quot; progid=&quot;EP_GraphicDsObjects.EP_BaseDataProjectHeader.1&quot; hetero=&quot;yes&quot;&gt;
        '''      &lt;def_table id=&quot;10753FD4-0179-4825-89F9-ADAEAE8699D0&quot; name=&quot;XML\default&quot; type=&quot;vertical&quot; clsid=&quot;{CB23B6EA-630A-11D4-A3F1-000000000000}&quot; progid=&quot;ProjectData.EP_ProjectData.1&quot; size=&quot;13&quot;&gt;
        '''
        '''       
        '''         &lt;def_property  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property koala_xml() As String
            Get
                Return ResourceManager.GetString("koala_xml", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LimitForceBeamNL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LimitForceBeamNL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LinearCombination() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LinearCombination", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LineLoad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LineLoad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LineSupport() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LineSupport", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LoadCases() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LoadCases", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LoadGroup() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LoadGroup", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Node() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Node", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NodeSupport() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NodeSupport", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NonLinearCombination() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NonLinearCombination", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Opening() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Opening", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PointLoadBeam() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PointLoadBeam", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PointLoadPoint() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PointLoadPoint", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PressOnly() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PressOnly", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ProjectInfo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ProjectInfo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StabilityCombination() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StabilityCombination", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SurfaceLoad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SurfaceLoad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
